### PR TITLE
Lesson3 magic

### PR DESCRIPTION
**Pull request by JennHopkins**
Dude, I unbroke my machine - it's Miller time. (I'm going to go buy a lottery ticket, it's my lucky day!)ty

Anyhow, the file is in my lesson3magic branch. You have your selection of wonderful files to choose from: 
- index.html (homebase: for all our serious and discerning shoppers.)
-style.scss (where the real styling is happening! Where it's at, my friend!)
-style.css (pay no attention to the css file, these aren't the droids you're looking for)
-chi-town.js (Chicago: REPRESENT!!) Here are the manifold ES6 objects of delight and destruction. 

Enjoy!

### CODE REVIEW

**Comment by JennHopkins** [comment]
This needs to be reviewed - as it says above this, but I closed it because thought I needed to invite a collaborator (Patrick? Who is that?) Anyhow, here it is! Have fun!

**Comment by JennHopkins** [comment]
This has had conflicts resolved. Should be good to go.

**Comment by cherimarie** [comment]
Please open MRs to your own fork.

**Comment by JennHopkins** [comment]
> 
> 
> Please open MRs to your own fork.

Okay. What is an MR and how do I open it to my own fork?

**Comment by cherimarie** [comment]
@JennHopkins for the course setup, you should have forked this repo, so that you had a copy you owned. Then, you make merge requests (MRs) to that fork, rather than this, the upstream fork. There's instructions in the README of the repo, and you can talk to your instructor for more details.

**Comment by JennHopkins** [comment]
> 
> 
> @JennHopkins for the course setup, you should have forked this repo, so that you had a copy you owned. Then, you make merge requests (MRs) to that fork, rather than this, the upstream fork. There's instructions in the README of the repo, and you can talk to your instructor for more details.

What can I say? This has been forked. I was talked to about merging stuff into my personal repo instead of the Front End Design course, so that is what I did. I asked him if it was forked correctly he said yes and moved on. But if I want any further information (anything more descriptive than that), I'm not going to get it. He doesn't respond to requests for information - he ignores me.

**Pull request closed without merging**
